# Generated by Django 4.0.4 on 2022-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradHubApp', '0002_resourcecategory_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
