# Generated by Django 4.0.4 on 2022-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradHubApp', '0003_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='imageURL',
            field=models.URLField(null=True),
        ),
    ]
